### ISSUE TITLE
[back-end] bootstrap back-end application

### ISSUE THREAD

**Issue by BenoitSerrano** [fondation451/label#12]
# Context
We need a back-end application, so as to fetch the Oracle content, request the machine learning engine, and store it in the MongoDB database 

- [x] install Express
- [x] install GraphQL
- [x] setup an empty CourtDecision module

-----------------------
### Note
We use express for simplicity. The Nest.js config has been saved on the branch `save-nest-config`.

**Comment by fondation451** [comment]
@BenoitSerrano 
It is done, I close this issue.
