### ISSUE TITLE
"Raise a problem" button

### ISSUE THREAD

**Issue by elRomano** [fondation451/label#175]
## Context
If at anytime a user cannot perform its action or sees a bug, he can send a message to the admin and (optionnally) skip to the next decision.
## Spec
A click on this button opens a panel displaying a form with :
- a classic dropdown "type de problème" : "Bug", "problème lié à l'annotation","suggestion"
- a long text field "description"
- an unchecked checkbox named "ce problème m'empêche de finaliser cette décision" that changes the send button label to "envoyer et passer la décision"
- a send button named "Envoyer"

![image](https://user-images.githubusercontent.com/25462034/96097193-f917b900-0ed0-11eb-8d9b-f2f5aa9b85b6.png)

**Comment by fondation451** [comment]
@BenoitSerrano 
I will introduce a new collection:  `problemReport`
```js
type problemReport = {
  _id: "id",
  assignationId: "id",
  type: "bug" | "annotationProblem" | "suggestion",
  text: "string",
}
```

**Comment by fondation451** [comment]
Done
