### ISSUE TITLE
Better readability in the decision content

### ISSUE THREAD

**Issue by elRomano** [fondation451/label#189]
## Context
We need to have the same text (font, letter-spacing, and size).
## Spec
The font is the Courier New, size 16px.

How it is now :
![image](https://user-images.githubusercontent.com/25462034/95954074-0c585500-0dfb-11eb-8e10-e506d8f84014.png)

How it should be :
![image](https://user-images.githubusercontent.com/25462034/95954194-36117c00-0dfb-11eb-8eaf-426f4dc86a47.png)

**Comment by fondation451** [comment]
Done
