### ISSUE TITLE
Create new annotation

### ISSUE THREAD

**Issue by elRomano** [fondation451/label#245]
## Context
We need to be able to create new annotation from scratch.
## Spec
When selecting content a tooltip menu appear with the following content :
-  number of words with the same characters (be careful with word boundaries management : https://github.com/fondation451/label/issues/237)
- A "apply to all" checkbox
- A dropdown with the category list

A click outside the tooltip makes it disappear

**Comment by fondation451** [comment]
@elRomano 
Pour l'instant, on peut ajouter une annotation.
Il n'y a pas : 
- le compteur de mots
- la checkbox

**Comment by elRomano** [comment]
@fondation451 Ok. On fait un autre ticket ou on laisse celui-là ouvert ? Un autre c'est peut-être mieux non ?

**Comment by fondation451** [comment]
@BenoitSerrano 
On peut en faire un autre, c'est mieux. Je te laisse le créer ?

**Comment by fondation451** [comment]
Done
