### ISSUE TITLE
courtDecision data type

### ISSUE THREAD

**Issue by fondation451** [fondation451/label#34]
# Context

The court decisions are our main object.
They come from two different data base: Jurinet and Jurica.
We then send them to the NLP engine for annotation. It need several information in order to work: the courtDecision (simple text), the metadata, the id, the data, and the source (Jurinet or Jurica).

The courtDecision can come from the database in xml or in html. But we will send back to the database only in xml format.

# Spec

I propose this format for courtDecision:

```
{
  date: date,
  footer: string, // footer of the xml file
  header: string, // header of the xml file
  _id: ObjectID,
  metadata: string,
  oracleId: string, // Oracle id
  source: string, // Jurinet or Jurica
  text: string, // the text of the court decision
}
```

**Comment by fondation451** [comment]
@BenoitSerrano What do you think?

**Comment by BenoitSerrano** [comment]
Ok with that model

**Comment by fondation451** [comment]
Done
