### ISSUE TITLE
Généraliser Label ?

### ISSUE THREAD

**Issue by fondation451** [fondation451/label#69]
Dans l'intitulé du défi, il était indiqué que le projet pourrait a terme sortir de la cour de cassation et traité autre chose que des décisions de justice.

Pour l'instant, on est très axé sur le fait que cela traite uniquement des courtDecisions. Mais cela ne pourrait pas juste traiter du texte ? Cela nous emanciperait de la notion de court décision dans core et dans le front. Les court décision ne serait alors présente que dans le backend.

Cela permettrait d'exporter le client et core vers d'autres administration qui n'auraient besoin que de réécrire le backend.

Cela ne peut marcher que si l'on a pas besoin de savoir que le texte a annoter est une court décision côté client.

@BenoitSerrano qu'en penses tu ? Si l'on décidé (et que l'on peut) généraliser, il faudrait le prévoir dès le début.
Je ne suis pas sûr encore que ce soit possible/intéressant de le faire.

**Comment by fondation451** [comment]
Proposition de découpage en paquets :
- agnostique
  -- client
  -- backend
  -- core (contient une définition du connecter générique)
- spécifique
  -- jurinet connecter (import/export)
  -- jurica connecter (import/export)
  -- server ---> instanciation du backend avec les connecters perso

**Comment by fondation451** [comment]
Pour moi, ce qui est spécifique à la cour de cassation, c'est : 
- la manière de récupérer les document à anonymiser (connecteur à Jurinet/Jurica)
- la manière de récupérer des annotations et un rapport (connecteur au moteur NLP)
- le type de donnée que l'on traite (ici des décisions de justice). Cela n'est pas utilisé pour l'instant, mais cela pourra être utile dans la suite pour mettre en place des "folder" de texte ou autre.

Le reste est générique et ne doit traiter que du texte : 
- la logique métier (annotation, document, rapport, utilisateur, statistique,...)
- le backend
- le client

Ces composants génériques seront paramétrés pour donner le backend et le client de la cour de cassation.

Je propose donc le découpage en paquet npm suivant : 
```
packages/
  generic/
    backend/
    client/
    core/
  courtOfCassation/
    jurinetConnector/
    juricaConnector/
    nlpAnnotator/
    courtOfCassationBackend/
    courtOfCassationClient/
```

Comme cela, l'application pourrait être repris par d'autres administration facilement. Il n'auront qu'à charger les paquets génériques (qui seront publiques) et à implementer les connecteurs spécifiques à leur infrastructure de donnée.

@BenoitSerrano Qu'en penses tu ?

**Comment by fondation451** [comment]
@BenoitSerrano 
Dans notre cas, on peut regrouper les connecteurs dans un seul paquet connecteur si on le souhaite

**Comment by BenoitSerrano** [comment]
C'est une archi qui me convient
Je pense qu'on peut laisser courDeCassation non traduit (en anglais on dit "cour de Cassation").
Normalement je ne crois pas qu'il y ait besoin de courtOfCassationBackend et Client, si les seules infos métiers sont les connecteurs et le moteur NLP. Mais s'il y a effectivement besoin ça me va de l'appeler comme ça

**Comment by fondation451** [comment]
@BenoitSerrano 
Très bien, je vais écrire les premiers tickets de migration.

**Comment by fondation451** [comment]
Done
